name: moinsen_supagen
description: Generate supabase helper code.
version: 0.2.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  antlr4:
  args:
  cli_completion: 
  equatable:
  http:
  json_annotation:
  mason_logger:
  path:
  pub_updater: 
  realtime_client: ^2.0.0
  simple_mustache: ^2.1.0
  storage_client: 2.0.1
  supabase_flutter: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  json_serializable:
  mocktail: ^1.0.0
  test: ^1.24.6
  very_good_analysis: ^5.1.0


executables:
  moinsen_supagen:
  
