name: moinsen_supagen
description: Generate supabase helper code.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  antlr4:
  args: ^2.4.1
  cli_completion: ^0.3.0
  http: ^1.1.0
  mason_logger: ^0.2.5
  path:
  pub_updater: ^0.3.1
  supabase: ^1.11.9
  
dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.24.6
  very_good_analysis: ^5.1.0

executables:
  moinsen_supagen:
  
