erDiagram
	CME_EDGES {
		string color  
		datetime created_at  
		string description  
		string direction  
		string id PK 
		string name  
		int thickness  
		datetime updated_at  
	}

	CME_IDEA_ITEMS }O--O{ CME_IDEAS, CME_IDEA_ITEMS }O--O{ CME_ITEMS: TBD
	CME_IDEA_ITEMS {
		datetime created_at  
		string id PK 
		string id_idea  
		string id_item FK 
		datetime updated_at  
	}

	CME_IDEA_VERSIONS }O--O{ CME_IDEAS: TBD
	CME_IDEA_VERSIONS {
		datetime created_at  
		string description  
		string id PK 
		string id_idea  
		string title  
		datetime updated_at  
		int version  
	}

	CME_IDEAS {
		datetime created_at  
		string description  
		string id PK 
		string title  
	}

	CME_ITEM_RELATIONS }O--O{ CME_EDGES, CME_ITEM_RELATIONS }O--O{ CME_ITEMS: TBD
	CME_ITEM_RELATIONS {
		datetime created_at  
		string id PK 
		string id_child_item FK 
		string id_edge FK 
		string id_parent_item FK 
		datetime updated_at  
	}

	CME_ITEMS }O--O{ CME_LOCATIONS, CME_ITEMS }O--O{ CME_PROFILES: TBD
	CME_ITEMS {
		string attachments  
		string category  
		string classification  
		datetime created_at  
		string data  
		string description  
		datetime end_date  
		string id PK 
		int id_location FK 
		string id_user FK 
		string notes  
		string origin  
		string priority  
		datetime start_date  
		string tags  
		string text  
		string title  
		datetime updated_at  
	}

	CME_LOCATIONS }O--O{ CME_PROFILES: TBD
	CME_LOCATIONS {
		datetime created_at  
		int id PK 
		string id_google_place  
		string id_user FK 
		string name  
		datetime update_at  
	}

	CME_NODE_PAGES }O--O{ CME_NODE_PAGES: TBD
	CME_NODE_PAGES {
		string checksum  
		int id PK 
		int id_parent_page FK 
		string meta  
		string path  
		string source  
		string type  
	}

	CME_NODE_PAGES_SECTION }O--O{ CME_NODE_PAGES: TBD
	CME_NODE_PAGES_SECTION {
		string content  
		string embedding  
		string heading  
		int id PK 
		int id_page FK 
		string slug  
		int token_count  
	}

	CME_PROFILES {
		string avatar_url  
		datetime created_at  
		string full_name  
		string id FK 
		string id_user FK 
		datetime updated_at  
		string username  
		string website  
	}

	CME_RECORDINGS }O--O{ CME_PROFILES: TBD
	CME_RECORDINGS {
		datetime created_at  
		string id PK 
		string id_user FK 
		string language  
		string text  
		datetime updated_at  
		string url  
	}

	CME_SCORES }O--O{ CME_IDEAS: TBD
	CME_SCORES {
		datetime created_at  
		string id PK 
		string id_idea  
		string score_type  
		int score_value  
		datetime updated_at  
	}

