erDiagram
	Post {
		int authorid FK "NULLABLE, , , "
		string content  "NULLABLE, , , "
		datetime createdat  ", , , "
		int id PK ", , , "
		bool published  ", , , "
		string title  ", , , "
		datetime updatedat  ", , , "
		int viewcount  ", , , "
	}

	User {
		string email  ", , , "
		int id PK ", , , "
		string name  "NULLABLE, , , "
	}

